# Generated by Django 4.1.5 on 2024-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftrack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
