# Generated by Django 4.1.5 on 2024-11-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_stafftrack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftrack',
            name='logout_time',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00'),
        ),
        migrations.AlterField(
            model_name='stafftrack',
            name='username',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
