# Generated by Django 4.1.5 on 2024-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_stafftrack_logout_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftrack',
            name='logout_time',
            field=models.DateTimeField(blank=True, default='1980-01-01 12:00:00'),
        ),
    ]
