# Generated by Django 4.1.5 on 2024-11-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_stafflate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflate',
            name='late_diff',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stafftrack',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
