# Generated by Django 4.1.5 on 2024-11-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_stafflate_late_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflate',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
