# Generated by Django 4.1.5 on 2024-11-25 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_stafflate_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffvacation',
            name='vacationTime',
            field=models.CharField(default='360:00:00', max_length=150),
        ),
        migrations.CreateModel(
            name='staffRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestedVacationTime', models.CharField(max_length=150)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
