# Generated by Django 4.1.5 on 2024-11-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_staffrequest_approved_staffrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
