# Generated by Django 4.1.5 on 2024-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_staffrequest_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
