# Generated by Django 4.1.5 on 2024-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_staffrequest_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrequest',
            name='requestedVacationTime',
            field=models.IntegerField(max_length=150),
        ),
    ]
