# Generated by Django 4.1.5 on 2024-11-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_staffrequest_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffrequest',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
